# This is a hack!
#
# Because of the autogenerated C++ code, compiling bm puts a lot of
# pressure on the memory in the host, so -j1 is not about the CPU, but
# about the available memory. But using -j1 on machines with enough
# memory causes the compilatin to take ages. If you choose to dedicate
# less than 1 GB of RAM to the machine where you do *actual* *work*, you
# get what you asked for.
MEM := $(shell grep ^MemTotal: /proc/meminfo  | tr -s ' ' | cut -d ' ' -f 2)
LOW_MEM_OPT := $(shell test $(MEM) -lt 1048576 && echo -j1)

all: build
	@echo Done.

build:
	@$(MAKE) $(LOW_MEM_OPT) -C bm PFX=$(PFX)

install:
	@$(MAKE) -C bm $@

clean:
	@$(MAKE) -C bm $@

distclean: clean
	$(MAKE) -C bm $@

.PHONY: all build clean distclean install
