VERBOSE := 1
TOPSRC := $(CURDIR)
PD_MK_DIR := $(TOPSRC)/submodules/p4c-bm/pd_mk

export VERBOSE
export TOPSRC
export PD_MK_DIR

all: build
	@echo Done.

build:
	# Because of the autogenerated C++ code, compiling this puts a
	# lot of pressure on the memory in the host, so -j1 is not about
	# the CPU, but about the available memory.
	$(MAKE) -j1 -C $(CURDIR)/targets/switch/bmv2 bm

install:
	install -m 0755 -o root -g root -d ${DESTDIR}/${prefix}/sbin

	install -m 0755 -o root -g root \
		$(CURDIR)/submodules/bm/targets/simple_switch/simple_switch \
		${DESTDIR}/${prefix}/sbin/bmv2

clean:
	$(MAKE) -C $(CURDIR)/submodules/bm $@
	$(MAKE) -C $(CURDIR)/submodules/p4c-bm/pd_mk $@
	$(MAKE) -C $(CURDIR)/targets/switch/bmv2 $@

distclean: clean
	$(MAKE) -C $(CURDIR)/submodules/bm $@
	$(MAKE) -C $(CURDIR)/submodules/p4c-bm/pd_mk $@

.PHONY: all build clean distclean
