VERBOSE := 1

TOPSRC := $(CURDIR)

P4C_BM_DIR := $(TOPSRC)/submodules/p4c-bm

PD_MK_DIR := $(P4C_BM_DIR)/pd_mk

BMV2_TARGET_NAME := switch
BMV2_TARGET_DIR := $(TOPSRC)/targets/$(BMV2_TARGET_NAME)/bmv2

USR_DIR := $(DESTDIR)$(prefix)
INC_DIR := $(USR_DIR)/include
LIB_DIR := $(USR_DIR)/lib
SBIN_DIR := $(USR_DIR)/sbin
SHARE_DIR := $(USR_DIR)/share/p4

export VERBOSE
export TOPSRC
export PD_MK_DIR

# This is a hack!
#
# Because of the autogenerated C++ code, compiling bm puts a lot of
# pressure on the memory in the host, so -j1 is not about the CPU, but
# about the available memory. But using -j1 on machines with enough
# memory causes the compilatin to take ages. If you choose to dedicate
# less than 1 GB of RAM to the machine where you do *actual* *work*, you
# get what you asked for.
MEM := $(shell grep ^MemTotal: /proc/meminfo  | tr -s ' ' | cut -d ' ' -f 2)
LOW_MEM_OPT := $(shell test $(MEM) -lt 1048576 && echo -j1)

all: build
	@echo Done.

build:
	$(MAKE) $(LOW_MEM_OPT) -C $(BMV2_TARGET_DIR) bm

install:
	install -m 0755 -o root -g root -d $(SBIN_DIR)
	install -m 0755 -o root -g root \
		$(BMV2_TARGET_DIR)/$(BMV2_TARGET_NAME)_bmv2 \
		$(SBIN_DIR)/

	install -m 0755 -o root -g root -d $(USR_DIR)
	tar -C $(BMV2_TARGET_DIR)/build/bmv2_pd -cf - include lib | \
		tar -C $(USR_DIR)/ -xvpf -

	install -m 0755 -o root -g root -d $(SHARE_DIR)
	install -m 0644 -o root -g root \
		$(BMV2_TARGET_DIR)/$(BMV2_TARGET_NAME)_bmv2.json \
		$(SHARE_DIR)/

clean:
	$(MAKE) -C $(TOPSRC)/submodules/bm $@
	$(MAKE) -C $(TOPSRC)/submodules/p4c-bm/pd_mk $@
	$(MAKE) -C $(BMV2_TARGET_DIR) $@

distclean: clean
	$(MAKE) -C $(TOPSRC)/submodules/bm $@
	$(MAKE) -C $(TOPSRC)/submodules/p4c-bm/pd_mk $@

.PHONY: all build clean distclean
